# Generated by Django 5.0.6 on 2024-06-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='Обо мне'),
        ),
        migrations.AddField(
            model_name='user',
            name='inst_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на инст'),
        ),
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Своя ссылка'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на линкедин'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на тг'),
        ),
    ]
