# Generated by Django 5.0.6 on 2024-06-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_about_me_user_inst_link_user_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='inst_link',
        ),
    ]
